fix indent on ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -150,10 +150,10 @@ jobs:
                     
       - name: 'Run Break Check'
         shell: 'bash'
-          run: |
-            set +e
-            BREAK_CHECK=$(buf breaking --against https://github.com/kiyani-org/proto-solution.git#branch=main,ref=HEAD~1)
-            if ! [[ -z "${BREAK_CHECK}" ]]; then
-              echo "::error::$BREAK_CHECK"
-              exit 1
-            fi
+        run: |
+          set +e
+          BREAK_CHECK=$(buf breaking --against https://github.com/kiyani-org/proto-solution.git#branch=main,ref=HEAD~1)
+          if ! [[ -z "${BREAK_CHECK}" ]]; then
+            echo "::error::$BREAK_CHECK"
+            exit 1
+          fi
