add breaking check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -129,31 +129,31 @@ jobs:
             exit 1
           fi
 
-  # breaking:
-  #   runs-on: 'ubuntu-latest'
-  #   needs: 'build'
-  #   steps:
-  #     - name: 'Checkout PR branch'
-  #       uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3
-  #       with:
-  #         ref: '${{ github.event.pull_request.head.ref }}'
+  breaking:
+    runs-on: 'ubuntu-latest'
+    needs: 'build'
+    steps:
+      - name: 'Checkout PR branch'
+        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3
+        with:
+          ref: '${{ github.event.pull_request.head.ref }}'
 
-  #     - name: 'Setup Buf CLI'
-  #       uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
-  #       with:
-  #         download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
-  #         install_path: '${{ runner.temp }}/.buf'
-  #         binary_subpath: 'buf/bin/buf'
-  #         checksum: '${{ env.BUF_CHECKSUM }}'
-  #         cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
-  #         add_to_path: true
+      - name: 'Setup Buf CLI'
+        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
+        with:
+          download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
+          install_path: '${{ runner.temp }}/.buf'
+          binary_subpath: 'buf/bin/buf'
+          checksum: '${{ env.BUF_CHECKSUM }}'
+          cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
+          add_to_path: true
 
-  #     - name: 'Run Break Check'
-  #       shell: 'bash'
-  #       run: |
-  #         set +e
-  #         BREAK_CHECK=$(buf lint --against https://github.com/kiyani-org/proto-solution.git#branch=main,ref=HEAD~1)
-  #         if ! [[ -z "${BREAK_CHECK}" ]]; then
-  #           echo "::error::$BREAK_CHECK"
-  #           exit 1
-  #         fi
+      - name: 'Run Break Check'
+        shell: 'bash'
+        run: |
+          set +e
+          BREAK_CHECK=$(buf lint --against https://github.com/kiyani-org/proto-solution.git#branch=main,ref=HEAD~1)
+          if ! [[ -z "${BREAK_CHECK}" ]]; then
+            echo "::error::$BREAK_CHECK"
+            exit 1
+          fi
