break check with cli

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -149,6 +149,12 @@ jobs:
           add_to_path: true
                     
       - name: 'Run Break Check'
-        uses: bufbuild/buf-breaking-action@f47418c81c00bfd65394628385593542f64db477 # ratchet:bufbuild/buf-breaking-action@v1
-        with:
+        shell: 'bash'
           against: 'https://github.com/kiyani-org/proto-solution.git#branch=main,ref=HEAD~1'
+          run: |
+            set +e
+            BREAK_CHECK=$(buf lint)
+            if ! [[ -z "${BREAK_CHECK}" ]]; then
+              echo "::error::$BREAK_CHECK"
+              exit 1
+            fi
