test uploading to new node gar

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,11 +15,11 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  DEFAULT_GO_VERSION: '1.21'
-  PROTOTOOL_VERSION: '1.10.0' # this is the last released version before the project was completed
+  GO_VERSION: '1.21'
   PROTOBUF_VERSION: '24.3'
-  PROTOC_GEN_GO_PLUGIN_VERSION: '1.31.0'
+  PROTOC_GEN_GO_VERSION: '1.31.0'
   BUF_VERSION: '1.28.1'
+  BUF_CHECKSUM: '278dd19ef5e6a504bdda16faf1488451'
 
 jobs:
   build:
@@ -31,21 +31,14 @@ jobs:
           ref: '${{ github.event.pull_request.head.ref }}'
 
       - name: 'Setup Buf CLI'
-        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:exclude
+        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
         with:
           download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
           install_path: '${{ runner.temp }}/.buf'
-          binary_subpath: '.'
-          checksum: '278dd19ef5e6a504bdda16faf1488451'
+          binary_subpath: 'buf/bin/buf'
+          checksum: '${{ env.BUF_CHECKSUM }}'
           cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
           add_to_path: true
-
-      - name: 'Set buf to path'
-        shell: 'bash'
-        env:
-          BUF_PATH: '${{ runner.temp }}/.buf/buf/bin'
-        run: |
-          echo "${BUF_PATH}" >> $GITHUB_PATH
 
       - name: 'Run Build'
         shell: 'bash'
@@ -62,33 +55,33 @@ jobs:
     needs: 'build'
     steps:
       - name: 'Checkout PR branch'
-        uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3
+        uses: 'actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11' # ratchet:actions/checkout@v4
         with:
           ref: '${{ github.event.pull_request.head.ref }}'
 
       - name: 'Setup Buf CLI'
-        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:exclude
+        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
         with:
           download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
           install_path: '${{ runner.temp }}/.buf'
-          binary_subpath: '.'
-          checksum: '278dd19ef5e6a504bdda16faf1488451'
+          binary_subpath: 'buf/bin/buf'
+          checksum: '${{ env.BUF_CHECKSUM }}'
           cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
           add_to_path: true
 
-      - name: 'Set buf to path'
+      - name: 'Run Lint'
         shell: 'bash'
-        env:
-          BUF_PATH: '${{ runner.temp }}/.buf/buf/bin'
         run: |
-          echo "${BUF_PATH}" >> $GITHUB_PATH
-
-      - name: 'Run Linter'
-        uses: 'bufbuild/buf-lint-action@044d13acb1f155179c606aaa2e53aea304d22058' # ratchet:bufbuild/buf-lint-action@v1
+          set +e
+          LINT_CHECK=$(buf lint)
+          if ! [[ -z "${LINT_CHECK}" ]]; then
+            echo "::error::$LINT_CHECK"
+            exit 1
+          fi
 
   regenerate:
     runs-on: 'ubuntu-latest'
-    needs: 'lint'
+    needs: 'build'
     steps:
       - name: 'Checkout PR branch'
         uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3
@@ -98,27 +91,20 @@ jobs:
       - name: 'Setup Go'
         uses: 'actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe' # ratchet:actions/setup-go@v4
         with:
-          go-version: ${{ env.DEFAULT_GO_VERSION }}
+          go-version: ${{ env.GO_VERSION }}
 
       - name: 'Setup Buf CLI'
-        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:exclude
+        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
         with:
           download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
           install_path: '${{ runner.temp }}/.buf'
-          binary_subpath: '.'
-          checksum: '278dd19ef5e6a504bdda16faf1488451'
+          binary_subpath: 'buf/bin/buf'
+          checksum: '${{ env.BUF_CHECKSUM }}'
           cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
           add_to_path: true
           
-      - name: 'Set buf to path'
-        shell: 'bash'
-        env:
-          BUF_PATH: '${{ runner.temp }}/.buf/buf/bin'
-        run: |
-          echo "${BUF_PATH}" >> $GITHUB_PATH
-
       - name: 'Install protobuf'
-        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:exclude
+        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
         with:
           download_url: 'https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOBUF_VERSION }}/protoc-${{ env.PROTOBUF_VERSION }}-linux-x86_64.zip'
           install_path: '${{ runner.temp }}/.protoc'
@@ -129,7 +115,7 @@ jobs:
 
       - name: 'Install protoc-gen-go'
         run: |
-          go install google.golang.org/protobuf/cmd/protoc-gen-go@v${{ env.PROTOC_GEN_GO_PLUGIN_VERSION }}
+          go install google.golang.org/protobuf/cmd/protoc-gen-go@v${{ env.PROTOC_GEN_GO_VERSION }}
 
       - name: 'Run Generate'
         shell: 'bash'
@@ -145,7 +131,7 @@ jobs:
 
   breaking:
     runs-on: 'ubuntu-latest'
-    needs: 'regenerate'
+    needs: 'build'
     steps:
       - name: 'Checkout PR branch'
         uses: 'actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744' # ratchet:actions/checkout@v3
@@ -153,22 +139,15 @@ jobs:
           ref: '${{ github.event.pull_request.head.ref }}'
 
       - name: 'Setup Buf CLI'
-        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:exclude
+        uses: 'abcxyz/pkg/.github/actions/setup-binary@main' # ratchet:abcxyz/pkg/.github/actions/setup-binary@main
         with:
           download_url: 'https://github.com/bufbuild/buf/releases/download/v${{ env.BUF_VERSION }}/buf-Linux-x86_64.tar.gz'
           install_path: '${{ runner.temp }}/.buf'
-          binary_subpath: '.'
-          checksum: '278dd19ef5e6a504bdda16faf1488451'
+          binary_subpath: 'buf/bin/buf'
+          checksum: '${{ env.BUF_CHECKSUM }}'
           cache_key: '${{ runner.os }}_${{ runner.arch }}_buf_${{ env.BUF_VERSION }}'
           add_to_path: true
-          
-      - name: 'Set buf to path'
-        shell: 'bash'
-        env:
-          BUF_PATH: '${{ runner.temp }}/.buf/buf/bin'
-        run: |
-          echo "${BUF_PATH}" >> $GITHUB_PATH
-          
+                    
       - name: 'Run Break Check'
         uses: bufbuild/buf-breaking-action@f47418c81c00bfd65394628385593542f64db477 # ratchet:bufbuild/buf-breaking-action@v1
         with:
