Testing major version upgrades (#3)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,7 +4,14 @@ on:
   pull_request:
     branches:
       - 'main'
-  workflow_call:
+
+permissions:
+  contents: 'read'
+  id-token: 'write'
+
+concurrency:
+  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
+  cancel-in-progress: true
 
 env:
   DEFAULT_GO_VERSION: '1.21'
@@ -13,9 +20,71 @@ env:
   PROTOC_GEN_GO_PLUGIN_VERSION: '1.31'
 
 jobs:
+  store_proposed_proto_version:
+    runs-on: 'ubuntu-latest'
+    outputs:
+      proposed_proto_version: ${{ steps.capture.outputs.PROPOSED_PROTO_VERSION }}
+    steps:
+      - name: 'Checkout'
+        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
+      - name: 'Capture proposed version'
+        id: "capture"
+        run: |
+          echo "PROPOSED_PROTO_VERSION=$(yq eval '.proto_version' version.yaml)" >> $GITHUB_OUTPUT
+
+  store_latest_proto_version:
+    runs-on: 'ubuntu-latest'
+    needs: 'store_proposed_proto_version'
+    env:
+      PROPOSED_PROTO_VERSION: ${{ needs.store_proposed_proto_version.outputs.proposed_proto_version }}
+    outputs:
+      latest_proto_version: ${{ steps.capture.outputs.LATEST_PROTO_VERSION }}    
+    steps:
+      - name: 'Checkout'
+        uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
+        with:
+          ref: 'main'
+      - name: 'Capture latest version'
+        id: 'capture'
+        run: |
+          set +e
+          LATEST_PROTO_VERSION=$(yq eval '.proto_version' version.yaml) 
+          if ! [[ -z "${LATEST_PROTO_VERSION}" ]]; then
+            echo "LATEST_PROTO_VERSION=$LATEST_PROTO_VERSION" >> $GITHUB_OUTPUT
+          else
+            echo $PROPOSED_PROTO_VERSION
+            echo "LATEST_PROTO_VERSION=$PROPOSED_PROTO_VERSION" >> $GITHUB_OUTPUT
+          fi
+
+  major_version_diff:
+    runs-on: 'ubuntu-latest'
+    needs: 
+      - 'store_proposed_proto_version'      
+      - 'store_latest_proto_version'
+    env:
+      PROPOSED_PROTO_VERSION: ${{ needs.store_proposed_proto_version.outputs.proposed_proto_version }}
+      LATEST_PROTO_VERSION: ${{ needs.store_latest_proto_version.outputs.latest_proto_version }}
+    outputs:
+      major_version_change: ${{ steps.capture.outputs.MAJOR_VERSION_CHANGE }}  
+    steps:
+      - name: 'Compare major versions'
+        id: 'capture'
+        run: |
+          set +e
+          v_proposed=$(awk -F. '{print $1}' <<< $PROPOSED_PROTO_VERSION)
+          proposed=$(sed s/v//g <<< $v_proposed)
+
+          v_latest=$(awk -F. '{print $1}' <<< $LATEST_PROTO_VERSION)
+          latest=$(sed s/v//g <<< $v_latest)
+
+          echo "MAJOR_VERSION_CHANGE=$(expr $proposed - $latest)" >> $GITHUB_OUTPUT
+
   validate:
     runs-on: 'ubuntu-latest'
-
+    needs: 
+      - 'major_version_diff'
+      - 'store_proposed_proto_version'
+      - 'store_latest_proto_version'
     steps:
       - name: 'Checkout'
         uses: 'actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9' # ratchet:actions/checkout@v3
@@ -72,5 +141,16 @@ jobs:
           FILE_DIFF=$(git status --porcelain)
           if ! [[ -z "${FILE_DIFF}" ]]; then
             echo "::error::Generated proto files are out of sync, re-run script to reflect latest proto state"
+            exit 1
+          fi
+        
+      - name: 'Check for breaking changes'
+        if: ${{ needs.major_version_diff.outputs.major_version_change == 0 }}
+        run: |
+          set +e
+          echo ${{ needs.major_version_diff.outputs.major_version_change }}
+          BREAK_CHECK=$(prototool break check protos)
+          if ! [[ -z "${BREAK_CHECK}" ]]; then
+            echo "::error::$BREAK_CHECK"
             exit 1
           fi
